services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mafia
      POSTGRES_USER: mafia
      POSTGRES_PASSWORD: mafia
    volumes:
      - ".pgdata:/var/lib/postgresql@17/data/pgdata"
